<?php return array (
  'email_type' => '1',
  'email_safe' => '',
  'mail_address' => '',
  'smtp' => '',
  'smtp_user' => '',
  'smtp_pwd' => '',
  'smtp_port' => '',
  'order_by' => 'new',
  'name' => 'braveEC电子商务平台',
  'url' => 'http://www.bravesoft.com.cn',
  'master' => '',
  'qq' => '',
  'email' => '',
  'mobile' => '',
  'phone' => '',
  'address' => '',
  'site_footer_code' => '<div class="footer" style="text-align:center;">  <p class="links">   <a href="">关于我们</a>|<a href="">常见问题</a>|<a href="">安全交易</a>|<a href="">购买流程</a>|<a href="">如何付款</a>|<a href="">联系我们</a>|<a href="">合作提案</a> </p>  <p class="copyright">   Powered by <a href="http://www.bravesoft.com.cn">bravesoft</a>  </p>Copyright © 2007-2016 <a class="copyys" target="_blank" href="http://www.miibeian.gov.cn/">蜀ICP备00000001号</a></div>',
  'tax' => '10',
  'stockup_time' => '1',
  'index_seo_title' => 'braveEC开源商城系统',
  'index_seo_keywords' => '开源商城系统,开源网店系统,开源电子商务,商城系统源码,多用户商城源码',
  'index_seo_description' => 'braveEC是基于php开发b2c2c开源多用户商城系统,支持商家入驻,支持微商城,手机移动商城,APP商城多为一体的电子商务系统',
  'goods_no_pre' => 'SD',
  'commission' => '',
  'store_num_warning' => '1',
  'reg_option' => '0',
  'index_slide' => 'a:3:{i:0;a:3:{s:4:"name";s:27:"一体式电子商务平台";s:3:"url";s:28:"http://www.bravesoft.com.cn/";s:3:"img";s:17:"images/index1.jpg";}i:1;a:3:{s:4:"name";s:27:"稳定的网上商城系统";s:3:"url";s:28:"http://www.bravesoft.com.cn/";s:3:"img";s:17:"images/index2.jpg";}i:2;a:3:{s:4:"name";s:21:"多业务电商系统";s:3:"url";s:28:"http://www.bravesoft.com.cn/";s:3:"img";s:17:"images/index3.jpg";}}',
);